//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapleHome.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Void")]
        public string OpenAiToken {
            get {
                return ((string)(this["OpenAiToken"]));
            }
            set {
                this["OpenAiToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Url...")]
        public string QuickLink1 {
            get {
                return ((string)(this["QuickLink1"]));
            }
            set {
                this["QuickLink1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Url...")]
        public string QuickLink2 {
            get {
                return ((string)(this["QuickLink2"]));
            }
            set {
                this["QuickLink2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Url...")]
        public string QuickLink3 {
            get {
                return ((string)(this["QuickLink3"]));
            }
            set {
                this["QuickLink3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TokenSaved {
            get {
                return ((bool)(this["TokenSaved"]));
            }
            set {
                this["TokenSaved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Void")]
        public string QuickLink1Name {
            get {
                return ((string)(this["QuickLink1Name"]));
            }
            set {
                this["QuickLink1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Void")]
        public string QuickLink2Name {
            get {
                return ((string)(this["QuickLink2Name"]));
            }
            set {
                this["QuickLink2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Void")]
        public string QuickLink3Name {
            get {
                return ((string)(this["QuickLink3Name"]));
            }
            set {
                this["QuickLink3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Void")]
        public string QuickLink4Name {
            get {
                return ((string)(this["QuickLink4Name"]));
            }
            set {
                this["QuickLink4Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Void")]
        public string QuickLink5Name {
            get {
                return ((string)(this["QuickLink5Name"]));
            }
            set {
                this["QuickLink5Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Void")]
        public string QuickLink6Name {
            get {
                return ((string)(this["QuickLink6Name"]));
            }
            set {
                this["QuickLink6Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Url...")]
        public string QuickLink4 {
            get {
                return ((string)(this["QuickLink4"]));
            }
            set {
                this["QuickLink4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Url...")]
        public string QuickLink5 {
            get {
                return ((string)(this["QuickLink5"]));
            }
            set {
                this["QuickLink5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Url...")]
        public string QuickLink6 {
            get {
                return ((string)(this["QuickLink6"]));
            }
            set {
                this["QuickLink6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Path...")]
        public string QuickApp1 {
            get {
                return ((string)(this["QuickApp1"]));
            }
            set {
                this["QuickApp1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Path...")]
        public string QuickApp2 {
            get {
                return ((string)(this["QuickApp2"]));
            }
            set {
                this["QuickApp2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Path...")]
        public string QuickApp3 {
            get {
                return ((string)(this["QuickApp3"]));
            }
            set {
                this["QuickApp3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Path...")]
        public string QuickApp4 {
            get {
                return ((string)(this["QuickApp4"]));
            }
            set {
                this["QuickApp4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Path...")]
        public string QuickApp5 {
            get {
                return ((string)(this["QuickApp5"]));
            }
            set {
                this["QuickApp5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Path...")]
        public string QuickApp6 {
            get {
                return ((string)(this["QuickApp6"]));
            }
            set {
                this["QuickApp6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QuickApp1Name {
            get {
                return ((string)(this["QuickApp1Name"]));
            }
            set {
                this["QuickApp1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QuickApp2Name {
            get {
                return ((string)(this["QuickApp2Name"]));
            }
            set {
                this["QuickApp2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QuickApp3Name {
            get {
                return ((string)(this["QuickApp3Name"]));
            }
            set {
                this["QuickApp3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QuickApp4Name {
            get {
                return ((string)(this["QuickApp4Name"]));
            }
            set {
                this["QuickApp4Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QuickApp5Name {
            get {
                return ((string)(this["QuickApp5Name"]));
            }
            set {
                this["QuickApp5Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QuickApp6Name {
            get {
                return ((string)(this["QuickApp6Name"]));
            }
            set {
                this["QuickApp6Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyCTEZNcC9Le1GPrU7qdFruVyo52NzFUQtY")]
        public string YoutubeApiKey {
            get {
                return ((string)(this["YoutubeApiKey"]));
            }
            set {
                this["YoutubeApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyBr5FK93FZvdZtsEMV8uQX61k-4JTM--lA")]
        public string YoutubeApiKey2 {
            get {
                return ((string)(this["YoutubeApiKey2"]));
            }
            set {
                this["YoutubeApiKey2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyAZU3JNyiv-JiMZg5h7YIP3fUWZr0IwDM4")]
        public string YoutubeApiKey3 {
            get {
                return ((string)(this["YoutubeApiKey3"]));
            }
            set {
                this["YoutubeApiKey3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyAS-EGRuAajTCrjOD5k7pJhPvFc1dWH_1U")]
        public string YoutubeApiKey4 {
            get {
                return ((string)(this["YoutubeApiKey4"]));
            }
            set {
                this["YoutubeApiKey4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyBWpZx2jJl_gKneHMVKsKGIJvKO1Yjapp4")]
        public string YoutubeApiKey5 {
            get {
                return ((string)(this["YoutubeApiKey5"]));
            }
            set {
                this["YoutubeApiKey5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyAV_MAEY-AOpvWs6KrgigAUcqqxYInaTqo")]
        public string YoutubeApiKey6 {
            get {
                return ((string)(this["YoutubeApiKey6"]));
            }
            set {
                this["YoutubeApiKey6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyAf4B4EJLnL1FWi9np3Xh6zfW2BaYBDXGM")]
        public string YoutubeApiKey7 {
            get {
                return ((string)(this["YoutubeApiKey7"]));
            }
            set {
                this["YoutubeApiKey7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyAqUR0P7szTnmyv6AZb38JuuNycJVo12WU")]
        public string YoutubeApiKey8 {
            get {
                return ((string)(this["YoutubeApiKey8"]));
            }
            set {
                this["YoutubeApiKey8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyAaih4FrKO1MLdepApopbgjTNVdFHutenc")]
        public string YoutubeApiKey9 {
            get {
                return ((string)(this["YoutubeApiKey9"]));
            }
            set {
                this["YoutubeApiKey9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyBqTcC84xgHfn6uk3H0mNHlfesYNVtZaA4")]
        public string YoutubeApiKey10 {
            get {
                return ((string)(this["YoutubeApiKey10"]));
            }
            set {
                this["YoutubeApiKey10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyAOzDby3TIhafOjNAlJndXIfRRDI6Tmyr4")]
        public string YoutubeApiKey11 {
            get {
                return ((string)(this["YoutubeApiKey11"]));
            }
            set {
                this["YoutubeApiKey11"] = value;
            }
        }
    }
}
